<?php
declare(strict_types=1);
require_once __DIR__ . DIRECTORY_SEPARATOR . 'db.php';
require_once __DIR__ . DIRECTORY_SEPARATOR . 'auth.php';
requireUser();
?><!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CampusFlow — Proposer un cours</title><link rel="stylesheet" href="page-shell.css"><link rel="stylesheet" href="shared-pages.css"><link rel="stylesheet" href="modern.css"></head>
<body data-page="proposal"><div class="app-shell"><aside class="sidebar"><a class="brand" href="index.html"><span class="brand-mark">C</span><span>Campus<span>Flow</span></span></a><p class="sidebar-label">Espace étudiant</p><nav><a class="nav-item" href="index.html"><span>⌂</span> Vue d'ensemble</a><a class="nav-item" href="courses.html"><span>▣</span> Mes cours</a><a class="nav-item active" href="propose-course.php"><span>＋</span> Proposer un cours</a></nav></aside><main class="page-content"><section class="page-card"><h1 class="page-title">Proposer un cours</h1><p class="page-subtitle">Soumets une ressource à faire valider par l'administration.</p><form id="proposal-form"><label>Matière<input id="proposal-course" required placeholder="Ex. Microéconomie II"></label><label>Nom du cours<input id="proposal-title" required placeholder="Ex. Fiche de révision"></label><label>Type<select id="proposal-type"><option value="notion">Notion</option><option value="google-docs">Google Docs</option><option value="pdf">PDF</option><option value="gemini">Gemini Notebook</option><option value="other">Autre</option></select></label><label>Lien<input id="proposal-url" type="url" required placeholder="https://..."></label><button class="primary-button" type="submit">Envoyer la proposition</button><p id="proposal-status" class="calendar-status"></p></form></section></main></div><script>
document.querySelector('#proposal-form').addEventListener('submit', async event => { event.preventDefault(); const body={course:document.querySelector('#proposal-course').value.trim(),title:document.querySelector('#proposal-title').value.trim(),type:document.querySelector('#proposal-type').value,url:document.querySelector('#proposal-url').value.trim()}; const response=await fetch('/api/proposals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); document.querySelector('#proposal-status').textContent=response.ok?'Proposition envoyée à l’administration.':'Impossible d’envoyer la proposition.'; });
</script></body></html>
